[package]
name = "caprice"
description = "A REPL for Rust projects featuring an easy to use, zsh like autocomplete feature."
repository = "https://github.com/3kyro/caprice.git"
license = "MIT"
keywords = ["REPL", "autocomplete", "zsh"]
readme = "readme.md"
version = "0.4.0"
authors = ["Kyriakos Papachrysanthou"]
edition = "2021"
categories = ["command-line-interface", "command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
exitcode = "1.1.2"
regex = "1.10.2"

[dev-dependencies]
piston = "0.53.0"
piston2d-graphics = "0.42.0"
pistoncore-glutin_window = "0.68.0"
piston2d-opengl_graphics = "0.79.0"
