[package]
name = "caprice"
version = "0.1.0"
authors = ["kyro"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = {git = 'https://github.com/TimonPost/crossterm.git'}    
exitcode = "1.1.2"

