name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Formatting
      run: cargo fmt --all -- --check
    - name: Check lint
      run: cargo clippy
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
